//
//  File.swift
//  
//
//  Created by loaner on 8/6/22.
//

import Fluent
import Vapor

final class Professor: Model, Content{
    
    static let schema = "ece564server_professors"
    
    @ID(custom: "id", generatedBy: .random)
    var id: String?
    
    @Field(key: "username")
    var username: String
    
    @OptionalField(key: "password")
    var password: String?
    
    init(){
        
    }
    
    /*
     Initializer that creates a Professor object only with the username.
     Paramters: Username. The password and ID are generated by the code.
     The password is a SHA256 hashed value of the username provided
     */
    init(username: String){
        self.id = UUID().uuidString
        self.username = username
        let usernameData = Data(username.utf8)
        let usernameHashed = SHA256.hash(data: usernameData)
        self.password = usernameHashed.hex
    }
    
    /*
     Initializer which creates a Professor with the provided username and password.
     Parameters: username and password.
     ID is generated by the code.
     */
    init(username: String, password: String){
        self.id = UUID().uuidString
        self.username = username
        self.password = password
    }
    
}
